### ISSUE TITLE
Is there any recording for the presentation?

### ISSUE THREAD

**Issue by noklam** [svjan5/GNNs-for-NLP#3]
The slides seem to be very useful material, I am wondering is there recording from this presentation or similar presentation?

Thank you.

**Comment by svjan5** [comment]
Hi @noklam,
Yes, I will be made available in some time by EMNLP 2019 organizers. I will post the link here once it is public.

**Comment by pritam-dey3** [comment]
is it available yet?

**Comment by svjan5** [comment]
Thanks @pritam-dey3
